In [32]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [33]:
df=pd.read_excel(r"C:\Users\91636\OneDrive\Desktop\Data-Analytics-Portfolio\Python\ML_practice\Practice_data.xlsx")

In [34]:
df

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
0,1001,CSE,Male,82.0,7.5,68.0,9.0,78
1,1002,IT,Female,91.0,8.2,74.0,10.0,86
2,1003,ECE,Male,76.0,5.5,61.0,7.0,70
3,1004,AI&DS,Female,88.0,7.0,79.0,9.0,84
4,1005,BBA,Female,72.0,4.0,58.0,6.0,64
5,1006,CSE,Male,95.0,9.0,88.0,10.0,94
6,1007,IT,Female,67.0,3.5,52.0,5.0,59
7,1008,ECE,Male,84.0,6.5,70.0,8.0,77
8,1009,AI&DS,Female,79.0,6.0,66.0,8.0,73
9,1010,CSE,Female,93.0,8.5,82.0,10.0,90
10,1011,BBA,Male,69.0,4.5,55.0,6.0,62
11,1012,IT,Male,87.0,7.8,76.0,9.0,83
12,1013,ECE,Female,74.0,5.0,63.0,7.0,69
13,1014,AI&DS,Male,90.0,8.0,85.0,9.0,88
14,1015,CSE,Female,81.0,NaN,72.0,8.0,79
15,1016,IT,Male,78.0,5.8,NaN,7.0,72
16,1017,ECE,Female,NaN,6.2,67.0,8.0,75
17,1018,AI&DS,Male,86.0,7.2,73.0,NaN,82
18,1019,BBA,Female,65.0,3.0,49.0,5.0,55
19,1020,CSE,Male,89.0,7.5,81.0,9.0,86
20,1021,IT,Female,83.0,6.8,71.0,8.0,80
21,1022,ECE,Male,71.0,4.8,59.0,6.0,66
22,1023,AI&DS,Female,94.0,9.2,89.0,10.0,96
23,1024,CSE,Male,77.0,5.2,64.0,7.0,71
24,1025,BBA,Female,73.0,4.2,57.0,6.0,63
25,1006,CSE,Male,95.0,9.0,88.0,10.0,94
26,1012,IT,Male,87.0,7.8,76.0,9.0,83
27,1020,CSE,Male,89.0,7.5,81.0,9.0,86

In [35]:
df.shape

(28, 8)

In [36]:
df.dtypes

Student_ID                 int64
Department                   str
Gender                       str
Attendance_Pct           float64
Study_Hours_Per_Day      float64
Internal_Marks           float64
Assignments_Completed    float64
Final_Score                int64
dtype: object

In [37]:
df.isnull()

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,True,False,False,False
15,False,False,False,False,False,True,False,False
16,False,False,False,True,False,False,False,False
17,False,False,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False

In [38]:
df.isnull().sum()

Student_ID               0
Department               0
Gender                   0
Attendance_Pct           1
Study_Hours_Per_Day      1
Internal_Marks           1
Assignments_Completed    1
Final_Score              0
dtype: int64

In [39]:
df.Attendance_Pct

0     82.0
1     91.0
2     76.0
3     88.0
4     72.0
5     95.0
6     67.0
7     84.0
8     79.0
9     93.0
10    69.0
11    87.0
12    74.0
13    90.0
14    81.0
15    78.0
16     NaN
17    86.0
18    65.0
19    89.0
20    83.0
21    71.0
22    94.0
23    77.0
24    73.0
25    95.0
26    87.0
27    89.0
Name: Attendance_Pct, dtype: float64

In [40]:
df["Attendance_Pct"]=df["Attendance_Pct"].fillna(df['Attendance_Pct'].mean())

In [41]:
df["Attendance_Pct"]

0     82.000000
1     91.000000
2     76.000000
3     88.000000
4     72.000000
5     95.000000
6     67.000000
7     84.000000
8     79.000000
9     93.000000
10    69.000000
11    87.000000
12    74.000000
13    90.000000
14    81.000000
15    78.000000
16    82.037037
17    86.000000
18    65.000000
19    89.000000
20    83.000000
21    71.000000
22    94.000000
23    77.000000
24    73.000000
25    95.000000
26    87.000000
27    89.000000
Name: Attendance_Pct, dtype: float64

In [42]:
df["Attendance_Pct"]=df["Attendance_Pct"].fillna(df['Attendance_Pct'].median())
df["Attendance_Pct"]

0     82.000000
1     91.000000
2     76.000000
3     88.000000
4     72.000000
5     95.000000
6     67.000000
7     84.000000
8     79.000000
9     93.000000
10    69.000000
11    87.000000
12    74.000000
13    90.000000
14    81.000000
15    78.000000
16    82.037037
17    86.000000
18    65.000000
19    89.000000
20    83.000000
21    71.000000
22    94.000000
23    77.000000
24    73.000000
25    95.000000
26    87.000000
27    89.000000
Name: Attendance_Pct, dtype: float64

In [43]:
df["Study_Hours_Per_Day"]=df["Study_Hours_Per_Day"].fillna(df['Study_Hours_Per_Day'].median())
df["Study_Hours_Per_Day"]

0     7.5
1     8.2
2     5.5
3     7.0
4     4.0
5     9.0
6     3.5
7     6.5
8     6.0
9     8.5
10    4.5
11    7.8
12    5.0
13    8.0
14    6.8
15    5.8
16    6.2
17    7.2
18    3.0
19    7.5
20    6.8
21    4.8
22    9.2
23    5.2
24    4.2
25    9.0
26    7.8
27    7.5
Name: Study_Hours_Per_Day, dtype: float64

In [44]:
df["Internal_Marks"]=df["Internal_Marks"].fillna(df['Internal_Marks'].median())
df["Internal_Marks"]

0     68.0
1     74.0
2     61.0
3     79.0
4     58.0
5     88.0
6     52.0
7     70.0
8     66.0
9     82.0
10    55.0
11    76.0
12    63.0
13    85.0
14    72.0
15    71.0
16    67.0
17    73.0
18    49.0
19    81.0
20    71.0
21    59.0
22    89.0
23    64.0
24    57.0
25    88.0
26    76.0
27    81.0
Name: Internal_Marks, dtype: float64

In [45]:
df["Assignments_Completed"]=df["Assignments_Completed"].fillna(df['Assignments_Completed'].median())
df["Assignments_Completed"]

0      9.0
1     10.0
2      7.0
3      9.0
4      6.0
5     10.0
6      5.0
7      8.0
8      8.0
9     10.0
10     6.0
11     9.0
12     7.0
13     9.0
14     8.0
15     7.0
16     8.0
17     8.0
18     5.0
19     9.0
20     8.0
21     6.0
22    10.0
23     7.0
24     6.0
25    10.0
26     9.0
27     9.0
Name: Assignments_Completed, dtype: float64

In [46]:
df

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
0,1001,CSE,Male,82.000000,7.5,68.0,9.0,78
1,1002,IT,Female,91.000000,8.2,74.0,10.0,86
2,1003,ECE,Male,76.000000,5.5,61.0,7.0,70
3,1004,AI&DS,Female,88.000000,7.0,79.0,9.0,84
4,1005,BBA,Female,72.000000,4.0,58.0,6.0,64
5,1006,CSE,Male,95.000000,9.0,88.0,10.0,94
6,1007,IT,Female,67.000000,3.5,52.0,5.0,59
7,1008,ECE,Male,84.000000,6.5,70.0,8.0,77
8,1009,AI&DS,Female,79.000000,6.0,66.0,8.0,73
9,1010,CSE,Female,93.000000,8.5,82.0,10.0,90
10,1011,BBA,Male,69.000000,4.5,55.0,6.0,62
11,1012,IT,Male,87.000000,7.8,76.0,9.0,83
12,1013,ECE,Female,74.000000,5.0,63.0,7.0,69
13,1014,AI&DS,Male,90.000000,8.0,85.0,9.0,88
14,1015,CSE,Female,81.000000,6.8,72.0,8.0,79
15,1016,IT,Male,78.000000,5.8,71.0,7.0,72
16,1017,ECE,Female,82.037037,6.2,67.0,8.0,75
17,1018,AI&DS,Male,86.000000,7.2,73.0,8.0,82
18,1019,BBA,Female,65.000000,3.0,49.0,5.0,55
19,1020,CSE,Male,89.000000,7.5,81.0,9.0,86
20,1021,IT,Female,83.000000,6.8,71.0,8.0,80
21,1022,ECE,Male,71.000000,4.8,59.0,6.0,66
22,1023,AI&DS,Female,94.000000,9.2,89.0,10.0,96
23,1024,CSE,Male,77.000000,5.2,64.0,7.0,71
24,1025,BBA,Female,73.000000,4.2,57.0,6.0,63
25,1006,CSE,Male,95.000000,9.0,88.0,10.0,94
26,1012,IT,Male,87.000000,7.8,76.0,9.0,83
27,1020,CSE,Male,89.000000,7.5,81.0,9.0,86

In [47]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25     True
26     True
27     True
dtype: bool

In [48]:
duplicates = df[df.duplicated()]
print(duplicates)

    Student_ID Department Gender  Attendance_Pct  Study_Hours_Per_Day  \
25        1006        CSE   Male            95.0                  9.0
26        1012         IT   Male            87.0                  7.8
27        1020        CSE   Male            89.0                  7.5

    Internal_Marks  Assignments_Completed  Final_Score
25            88.0                   10.0           94
26            76.0                    9.0           83
27            81.0                    9.0           86

In [49]:
df

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
0,1001,CSE,Male,82.000000,7.5,68.0,9.0,78
1,1002,IT,Female,91.000000,8.2,74.0,10.0,86
2,1003,ECE,Male,76.000000,5.5,61.0,7.0,70
3,1004,AI&DS,Female,88.000000,7.0,79.0,9.0,84
4,1005,BBA,Female,72.000000,4.0,58.0,6.0,64
5,1006,CSE,Male,95.000000,9.0,88.0,10.0,94
6,1007,IT,Female,67.000000,3.5,52.0,5.0,59
7,1008,ECE,Male,84.000000,6.5,70.0,8.0,77
8,1009,AI&DS,Female,79.000000,6.0,66.0,8.0,73
9,1010,CSE,Female,93.000000,8.5,82.0,10.0,90
10,1011,BBA,Male,69.000000,4.5,55.0,6.0,62
11,1012,IT,Male,87.000000,7.8,76.0,9.0,83
12,1013,ECE,Female,74.000000,5.0,63.0,7.0,69
13,1014,AI&DS,Male,90.000000,8.0,85.0,9.0,88
14,1015,CSE,Female,81.000000,6.8,72.0,8.0,79
15,1016,IT,Male,78.000000,5.8,71.0,7.0,72
16,1017,ECE,Female,82.037037,6.2,67.0,8.0,75
17,1018,AI&DS,Male,86.000000,7.2,73.0,8.0,82
18,1019,BBA,Female,65.000000,3.0,49.0,5.0,55
19,1020,CSE,Male,89.000000,7.5,81.0,9.0,86
20,1021,IT,Female,83.000000,6.8,71.0,8.0,80
21,1022,ECE,Male,71.000000,4.8,59.0,6.0,66
22,1023,AI&DS,Female,94.000000,9.2,89.0,10.0,96
23,1024,CSE,Male,77.000000,5.2,64.0,7.0,71
24,1025,BBA,Female,73.000000,4.2,57.0,6.0,63
25,1006,CSE,Male,95.000000,9.0,88.0,10.0,94
26,1012,IT,Male,87.000000,7.8,76.0,9.0,83
27,1020,CSE,Male,89.000000,7.5,81.0,9.0,86

In [50]:
cleaned_data=df.drop_duplicates()
cleaned_data

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
0,1001,CSE,Male,82.000000,7.5,68.0,9.0,78
1,1002,IT,Female,91.000000,8.2,74.0,10.0,86
2,1003,ECE,Male,76.000000,5.5,61.0,7.0,70
3,1004,AI&DS,Female,88.000000,7.0,79.0,9.0,84
4,1005,BBA,Female,72.000000,4.0,58.0,6.0,64
5,1006,CSE,Male,95.000000,9.0,88.0,10.0,94
6,1007,IT,Female,67.000000,3.5,52.0,5.0,59
7,1008,ECE,Male,84.000000,6.5,70.0,8.0,77
8,1009,AI&DS,Female,79.000000,6.0,66.0,8.0,73
9,1010,CSE,Female,93.000000,8.5,82.0,10.0,90
10,1011,BBA,Male,69.000000,4.5,55.0,6.0,62
11,1012,IT,Male,87.000000,7.8,76.0,9.0,83
12,1013,ECE,Female,74.000000,5.0,63.0,7.0,69
13,1014,AI&DS,Male,90.000000,8.0,85.0,9.0,88
14,1015,CSE,Female,81.000000,6.8,72.0,8.0,79
15,1016,IT,Male,78.000000,5.8,71.0,7.0,72
16,1017,ECE,Female,82.037037,6.2,67.0,8.0,75
17,1018,AI&DS,Male,86.000000,7.2,73.0,8.0,82
18,1019,BBA,Female,65.000000,3.0,49.0,5.0,55
19,1020,CSE,Male,89.000000,7.5,81.0,9.0,86
20,1021,IT,Female,83.000000,6.8,71.0,8.0,80
21,1022,ECE,Male,71.000000,4.8,59.0,6.0,66
22,1023,AI&DS,Female,94.000000,9.2,89.0,10.0,96
23,1024,CSE,Male,77.000000,5.2,64.0,7.0,71
24,1025,BBA,Female,73.000000,4.2,57.0,6.0,63

In [51]:
x=cleaned_data.drop("Final_Score",axis=1)
x

,Student_ID,Department,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed
0,1001,CSE,Male,82.000000,7.5,68.0,9.0
1,1002,IT,Female,91.000000,8.2,74.0,10.0
2,1003,ECE,Male,76.000000,5.5,61.0,7.0
3,1004,AI&DS,Female,88.000000,7.0,79.0,9.0
4,1005,BBA,Female,72.000000,4.0,58.0,6.0
5,1006,CSE,Male,95.000000,9.0,88.0,10.0
6,1007,IT,Female,67.000000,3.5,52.0,5.0
7,1008,ECE,Male,84.000000,6.5,70.0,8.0
8,1009,AI&DS,Female,79.000000,6.0,66.0,8.0
9,1010,CSE,Female,93.000000,8.5,82.0,10.0
10,1011,BBA,Male,69.000000,4.5,55.0,6.0
11,1012,IT,Male,87.000000,7.8,76.0,9.0
12,1013,ECE,Female,74.000000,5.0,63.0,7.0
13,1014,AI&DS,Male,90.000000,8.0,85.0,9.0
14,1015,CSE,Female,81.000000,6.8,72.0,8.0
15,1016,IT,Male,78.000000,5.8,71.0,7.0
16,1017,ECE,Female,82.037037,6.2,67.0,8.0
17,1018,AI&DS,Male,86.000000,7.2,73.0,8.0
18,1019,BBA,Female,65.000000,3.0,49.0,5.0
19,1020,CSE,Male,89.000000,7.5,81.0,9.0
20,1021,IT,Female,83.000000,6.8,71.0,8.0
21,1022,ECE,Male,71.000000,4.8,59.0,6.0
22,1023,AI&DS,Female,94.000000,9.2,89.0,10.0
23,1024,CSE,Male,77.000000,5.2,64.0,7.0
24,1025,BBA,Female,73.000000,4.2,57.0,6.0

In [52]:
y=cleaned_data["Final_Score"]
print(y)

0     78
1     86
2     70
3     84
4     64
5     94
6     59
7     77
8     73
9     90
10    62
11    83
12    69
13    88
14    79
15    72
16    75
17    82
18    55
19    86
20    80
21    66
22    96
23    71
24    63
Name: Final_Score, dtype: int64

In [53]:
encode=LabelEncoder()

In [54]:
df["Gender_encoded"]=encode.fit_transform(df["Gender"])

In [55]:
df[["Gender","Gender_encoded"]]

    Gender  Gender_encoded
0     Male               1
1   Female               0
2     Male               1
3   Female               0
4   Female               0
5     Male               1
6   Female               0
7     Male               1
8   Female               0
9   Female               0
10    Male               1
11    Male               1
12  Female               0
13    Male               1
14  Female               0
15    Male               1
16  Female               0
17    Male               1
18  Female               0
19    Male               1
20  Female               0
21    Male               1
22  Female               0
23    Male               1
24  Female               0
25    Male               1
26    Male               1
27    Male               1

In [56]:
cleaned_data["Gender_encoded"]=encode.fit_transform(cleaned_data["Gender"])

In [57]:
cleaned_data[["Gender","Gender_encoded"]]

    Gender  Gender_encoded
0     Male               1
1   Female               0
2     Male               1
3   Female               0
4   Female               0
5     Male               1
6   Female               0
7     Male               1
8   Female               0
9   Female               0
10    Male               1
11    Male               1
12  Female               0
13    Male               1
14  Female               0
15    Male               1
16  Female               0
17    Male               1
18  Female               0
19    Male               1
20  Female               0
21    Male               1
22  Female               0
23    Male               1
24  Female               0

In [59]:
cleaned_data=pd.get_dummies(cleaned_data,columns=["Department"])

In [60]:
cleaned_data

,Student_ID,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score,Gender_encoded,Department_AI&DS,Department_BBA,Department_CSE,Department_ECE,Department_IT
0,1001,Male,82.000000,7.5,68.0,9.0,78,1,False,False,True,False,False
1,1002,Female,91.000000,8.2,74.0,10.0,86,0,False,False,False,False,True
2,1003,Male,76.000000,5.5,61.0,7.0,70,1,False,False,False,True,False
3,1004,Female,88.000000,7.0,79.0,9.0,84,0,True,False,False,False,False
4,1005,Female,72.000000,4.0,58.0,6.0,64,0,False,True,False,False,False
5,1006,Male,95.000000,9.0,88.0,10.0,94,1,False,False,True,False,False
6,1007,Female,67.000000,3.5,52.0,5.0,59,0,False,False,False,False,True
7,1008,Male,84.000000,6.5,70.0,8.0,77,1,False,False,False,True,False
8,1009,Female,79.000000,6.0,66.0,8.0,73,0,True,False,False,False,False
9,1010,Female,93.000000,8.5,82.0,10.0,90,0,False,False,True,False,False
10,1011,Male,69.000000,4.5,55.0,6.0,62,1,False,True,False,False,False
11,1012,Male,87.000000,7.8,76.0,9.0,83,1,False,False,False,False,True
12,1013,Female,74.000000,5.0,63.0,7.0,69,0,False,False,False,True,False
13,1014,Male,90.000000,8.0,85.0,9.0,88,1,True,False,False,False,False
14,1015,Female,81.000000,6.8,72.0,8.0,79,0,False,False,True,False,False
15,1016,Male,78.000000,5.8,71.0,7.0,72,1,False,False,False,False,True
16,1017,Female,82.037037,6.2,67.0,8.0,75,0,False,False,False,True,False
17,1018,Male,86.000000,7.2,73.0,8.0,82,1,True,False,False,False,False
18,1019,Female,65.000000,3.0,49.0,5.0,55,0,False,True,False,False,False
19,1020,Male,89.000000,7.5,81.0,9.0,86,1,False,False,True,False,False
20,1021,Female,83.000000,6.8,71.0,8.0,80,0,False,False,False,False,True
21,1022,Male,71.000000,4.8,59.0,6.0,66,1,False,False,False,True,False
22,1023,Female,94.000000,9.2,89.0,10.0,96,0,True,False,False,False,False
23,1024,Male,77.000000,5.2,64.0,7.0,71,1,False,False,True,False,False
24,1025,Female,73.000000,4.2,57.0,6.0,63,0,False,True,False,False,False

In [61]:
cleaned_data.head(5)

,Student_ID,Gender,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score,Gender_encoded,Department_AI&DS,Department_BBA,Department_CSE,Department_ECE,Department_IT
0,1001,Male,82.0,7.5,68.0,9.0,78,1,False,False,True,False,False
1,1002,Female,91.0,8.2,74.0,10.0,86,0,False,False,False,False,True
2,1003,Male,76.0,5.5,61.0,7.0,70,1,False,False,False,True,False
3,1004,Female,88.0,7.0,79.0,9.0,84,0,True,False,False,False,False
4,1005,Female,72.0,4.0,58.0,6.0,64,0,False,True,False,False,False

In [62]:
df["avg"]=df[["Attendance_Pct","Internal_Marks"]].mean(axis=1)

In [63]:
df["avg"]

0     75.000000
1     82.500000
2     68.500000
3     83.500000
4     65.000000
5     91.500000
6     59.500000
7     77.000000
8     72.500000
9     87.500000
10    62.000000
11    81.500000
12    68.500000
13    87.500000
14    76.500000
15    74.500000
16    74.518519
17    79.500000
18    57.000000
19    85.000000
20    77.000000
21    65.000000
22    91.500000
23    70.500000
24    65.000000
25    91.500000
26    81.500000
27    85.000000
Name: avg, dtype: float64

In [65]:
df["avg_max"]=df[["Attendance_Pct","Internal_Marks"]].max(axis=1)

In [66]:
df["avg_max"]

0     82.000000
1     91.000000
2     76.000000
3     88.000000
4     72.000000
5     95.000000
6     67.000000
7     84.000000
8     79.000000
9     93.000000
10    69.000000
11    87.000000
12    74.000000
13    90.000000
14    81.000000
15    78.000000
16    82.037037
17    86.000000
18    65.000000
19    89.000000
20    83.000000
21    71.000000
22    94.000000
23    77.000000
24    73.000000
25    95.000000
26    87.000000
27    89.000000
Name: avg_max, dtype: float64

In [70]:
df["Adm_date"]=pd.DataFrame(['2026-01-15', '2026-02-20', '2026-03-05'])

In [74]:
df["Adm_date"]=pd.to_datetime(df["Adm_date"])
df["Adm_date"].dtypes

dtype('<M8[us]')

In [72]:
#Some methods are not designed with data vectorization. So we need to apply for each. dt is an accessor from that we can access year,month
df["Adm_date"].dt.year

0     2026.0
1     2026.0
2     2026.0
3        NaN
4        NaN
5        NaN
6        NaN
7        NaN
8        NaN
9        NaN
10       NaN
11       NaN
12       NaN
13       NaN
14       NaN
15       NaN
16       NaN
17       NaN
18       NaN
19       NaN
20       NaN
21       NaN
22       NaN
23       NaN
24       NaN
25       NaN
26       NaN
27       NaN
Name: Adm_date, dtype: float64

In [73]:
df["Adm_date"].dt.month

0     1.0
1     2.0
2     3.0
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
20    NaN
21    NaN
22    NaN
23    NaN
24    NaN
25    NaN
26    NaN
27    NaN
Name: Adm_date, dtype: float64

In [68]:
(df[["Attendance_Pct","Internal_Marks"]]<50).sum(axis=1)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    1
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
dtype: int64